// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9Rzn1nZuRV8lpirswHyQORNt9TWAF7w',
    appId: '1:164573529000:web:8d49b1d3ef6c1b8002939d',
    messagingSenderId: '164573529000',
    projectId: 'salimshopapptest',
    authDomain: 'salimshopapptest.firebaseapp.com',
    storageBucket: 'salimshopapptest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHMgBocQDlxIJNsmfkqE-j1QTQsRCQ-qk',
    appId: '1:164573529000:android:2271bfce7c67eae302939d',
    messagingSenderId: '164573529000',
    projectId: 'salimshopapptest',
    storageBucket: 'salimshopapptest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUkJyObPJVi4m_p8Tj1Cv2_y6fdbRHpTk',
    appId: '1:164573529000:ios:e691ca0932d6b03502939d',
    messagingSenderId: '164573529000',
    projectId: 'salimshopapptest',
    storageBucket: 'salimshopapptest.appspot.com',
    androidClientId: '164573529000-fa9dnighdje5dcvhrlkh7hfiv5ka8gq9.apps.googleusercontent.com',
    iosClientId: '164573529000-q2ep1i8ms8rkaaahq55o9kl5kk0a4aq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUkJyObPJVi4m_p8Tj1Cv2_y6fdbRHpTk',
    appId: '1:164573529000:ios:e691ca0932d6b03502939d',
    messagingSenderId: '164573529000',
    projectId: 'salimshopapptest',
    storageBucket: 'salimshopapptest.appspot.com',
    androidClientId: '164573529000-fa9dnighdje5dcvhrlkh7hfiv5ka8gq9.apps.googleusercontent.com',
    iosClientId: '164573529000-q2ep1i8ms8rkaaahq55o9kl5kk0a4aq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
